simpler & more robust config and deploy routine

diff --git a/box/opt/main b/box/opt/main
--- a/box/opt/main
+++ b/box/opt/main
@@ -5,27 +5,46 @@ start_time=$(date +%s.%3N)
 for f in /opt/box/libs/* ; do source $f; done
 export PATH+=':/opt/box/bin'
 
+# Load and export configuration
+load_config() {
+    if [ -f /data/config/.env ]; then
+        
+        set -a # Enable automatic export of all variables
+        source /data/config/.env
+        set +a # Disable automatic export
+        
+        debug "Loaded and exported all configuration variables from /data/config/.env"
+    else
+        error "Config file /data/config/.env not found"
+        exit 1
+    fi
+}
+
+load_config
+
 main_usage() {
     echo "----------------- box -----------------" 
     echo "wrappers around various CLIs" 
     echo "box [-h] [-d] [command] ... "
     echo "    -h              : this helper"
+    echo "    -d              : enable debug mode"
     echo "    hello           : hello world"
-    echo "    backup          : backup & restore tools"
-    echo "    transfer        : transfer data from grosserver1.0 to grosserver2.0"
     echo "    ssh ...         : ssh wrapper"
     echo "    deploy ...      : deploy tools"
     echo "    terraform ...   : terraform wrappers"
+    echo "    dns ...         : DNS zone management"
 }
 
 while getopts "hd" option; do
 case ${option} in
     h) main_usage && exit 0 ;;
+    d) 
+        export DEBUG=1 
+        notice "debug mode on" ;
+    ;;
     *) usage && exit 1 ;;
     esac
 done
-
-if [ -n "${DEBUG}" ] ; then notice "debug mode on" ; fi 
 
 shift $(($OPTIND-1))
 CMD=${1} && shift 1
